In [1]:
import os
os.chdir("C:/Users/hp/Desktop/food deployment")

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
meal_info = pd.read_csv("meal_info.csv")
center_info = pd.read_csv("fulfilment_center_info.csv")
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [3]:
meal_info = pd.read_csv("meal_info.csv")
center_info = pd.read_csv("fulfilment_center_info.csv")

In [4]:
trainfinal = pd.merge(train, meal_info, on="meal_id", how="outer")
trainfinal = pd.merge(trainfinal, center_info, on="center_id", how="outer")
trainfinal.head()
trainfinal = trainfinal.drop(['center_id', 'meal_id'], axis=1)


In [5]:
cols = trainfinal.columns.tolist()
cols = cols[:2] + cols[9:] + cols[7:9] + cols[2:7]
trainfinal = trainfinal[cols]
trainfinal.head()

id  week  city_code  region_code center_type  op_area   category  \
0  1379560     1        647           56      TYPE_C      2.0  Beverages   
1  1018704     2        647           56      TYPE_C      2.0  Beverages   
2  1196273     3        647           56      TYPE_C      2.0  Beverages   
3  1116527     4        647           56      TYPE_C      2.0  Beverages   
4  1343872     5        647           56      TYPE_C      2.0  Beverages   

  cuisine  checkout_price  base_price  emailer_for_promotion  \
0    Thai          136.83      152.29                      0   
1    Thai          135.83      152.29                      0   
2    Thai          132.92      133.92                      0   
3    Thai          135.86      134.86                      0   
4    Thai          146.50      147.50                      0   

   homepage_featured  num_orders  
0                  0         177  
1                  0         323  
2                  0          96  
3                  0         163  
4                  0         215

In [6]:
from sklearn.preprocessing import LabelEncoder
lb1 = LabelEncoder()
trainfinal['center_type'] = lb1.fit_transform(trainfinal['center_type'])

lb2 = LabelEncoder()
trainfinal['category'] = lb1.fit_transform(trainfinal['category'])

lb3 = LabelEncoder()
trainfinal['cuisine'] = lb1.fit_transform(trainfinal['cuisine'])

In [7]:
trainfinal.head()

id  week  city_code  region_code  center_type  op_area  category  \
0  1379560     1        647           56            2      2.0         0   
1  1018704     2        647           56            2      2.0         0   
2  1196273     3        647           56            2      2.0         0   
3  1116527     4        647           56            2      2.0         0   
4  1343872     5        647           56            2      2.0         0   

   cuisine  checkout_price  base_price  emailer_for_promotion  \
0        3          136.83      152.29                      0   
1        3          135.83      152.29                      0   
2        3          132.92      133.92                      0   
3        3          135.86      134.86                      0   
4        3          146.50      147.50                      0   

   homepage_featured  num_orders  
0                  0         177  
1                  0         323  
2                  0          96  
3                  0         163  
4                  0         215

In [8]:
trainfinal33=trainfinal.iloc[:,:12].values
trainfinal33[:,4]

array([2., 2., 2., ..., 0., 0., 0.])

In [9]:
from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder()
x1=trainfinal33[:,4].reshape((-1,1))
z=oh.fit_transform(x1).toarray()
z

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [16]:
trainfinal33=np.delete(trainfinal33,4,axis=1)
trainfinal33=np.concatenate((z,trainfinal33),axis=1)

In [11]:
trainfinal2 = trainfinal.drop(['id'], axis=1)
correlation = trainfinal2.corr(method='pearson')
columns = correlation.nlargest(8, 'num_orders').index
columns

Index(['num_orders', 'homepage_featured', 'emailer_for_promotion', 'op_area',
       'cuisine', 'city_code', 'region_code', 'category'],
      dtype='object')

In [12]:
features = columns.drop(['num_orders'])
trainfinal3 = trainfinal[features]
X = trainfinal3.values
y = trainfinal['num_orders'].values

from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25)

In [20]:
from sklearn.tree import DecisionTreeRegressor
DT = DecisionTreeRegressor()
DT.fit(X_train, y_train)
y_pred = DT.predict(X_val)
y_pred[y_pred<0] = 0
from sklearn import metrics
print('RMSLE:', 100*np.sqrt(metrics.mean_squared_log_error(y_val, y_pred)))

RMSLE: 62.765882201870205


In [21]:
testfinal = pd.merge(test, meal_info, on="meal_id", how="outer")
testfinal = pd.merge(testfinal, center_info, on="center_id", how="outer")
testfinal = testfinal.drop(['meal_id', 'center_id'], axis=1)

tcols = testfinal.columns.tolist()
print(tcols)

['id', 'week', 'checkout_price', 'base_price', 'emailer_for_promotion', 'homepage_featured', 'category', 'cuisine', 'city_code', 'region_code', 'center_type', 'op_area']


In [22]:
tcols = tcols[:2] + tcols[8:] + tcols[6:8] + tcols[2:6]
testfinal = testfinal[tcols]

lb1 = LabelEncoder()
testfinal['center_type'] = lb1.fit_transform(testfinal['center_type'])

lb2 = LabelEncoder()
testfinal['category'] = lb1.fit_transform(testfinal['category'])

lb3 = LabelEncoder()
testfinal['cuisine'] = lb1.fit_transform(testfinal['cuisine'])

testfinal.head()

id  week  city_code  region_code  center_type  op_area  category  \
0  1028232   146        647           56            2      2.0         0   
1  1262649   147        647           56            2      2.0         0   
2  1453211   149        647           56            2      2.0         0   
3  1262599   150        647           56            2      2.0         0   
4  1495848   151        647           56            2      2.0         0   

   cuisine  checkout_price  base_price  emailer_for_promotion  \
0        3          158.11      159.11                      0   
1        3          159.11      159.11                      0   
2        3          157.14      158.14                      0   
3        3          159.14      157.14                      0   
4        3          160.11      159.11                      0   

   homepage_featured  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0

In [23]:
features

Index(['homepage_featured', 'emailer_for_promotion', 'op_area', 'cuisine',
       'city_code', 'region_code', 'category'],
      dtype='object')

In [25]:
testfinal33=testfinal.iloc[:,:12].values
testfinal33[:,4]

array([2., 2., 2., ..., 0., 0., 0.])

In [26]:
from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder()
x1=testfinal33[:,4].reshape((-1,1))
z=oh.fit_transform(x1).toarray()
z

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [27]:
testfinal33=np.delete(testfinal33,4,axis=1)
testfinal33=np.concatenate((z,testfinal33),axis=1)

In [28]:
X_test = testfinal[features].values
X_test

array([[  0. ,   0. ,   2. , ..., 647. ,  56. ,   0. ],
       [  0. ,   0. ,   2. , ..., 647. ,  56. ,   0. ],
       [  0. ,   0. ,   2. , ..., 647. ,  56. ,   0. ],
       ...,
       [  0. ,   0. ,   4.5, ..., 473. ,  77. ,   4. ],
       [  0. ,   0. ,   4.5, ..., 473. ,  77. ,   4. ],
       [  0. ,   0. ,   4.5, ..., 473. ,  77. ,   4. ]])

In [29]:
pred = DT.predict(X_test)
pred[pred<0] = 0
submit = pd.DataFrame({
    'id' : testfinal['id'],
    'num_orders' : pred
})

In [30]:
submit.to_csv("submission.csv", index=False)

In [31]:
submit.describe()

id    num_orders
count  3.257300e+04  32573.000000
mean   1.248476e+06    262.675825
std    1.441580e+05    364.613360
min    1.000085e+06     14.666667
25%    1.123969e+06     64.070588
50%    1.247296e+06    148.752577
75%    1.372971e+06    321.400735
max    1.499996e+06   5997.947368